# wavesets.py
- zombieriot.phrases.zombienames.txt
- zombieriot.phrases.item.gift.desc.txt
- zombieriot.phrases.txt
- zombieriot.phrases.rogue.txt
- zombieriot.phrases.rogue.paradox.txt
- zombieriot.phrases.rogue.rift.txt
- zombieriot.phrases.status_effects.txt # + status_effects.py
- zombieriot.phrases.construction.txt
- zombieriot.phrases.dungeon.txt
# weapon.py
- zombieriot.phrases.weapons.description.txt
- zombieriot.phrases.weapons.txt
# skilltree.py
- zombieriot.phrases.skilltree.txt
