# Hardcoded skilltree position offsets as to prevent overlaps
ab: 7 # Health Up
# and it's descendants...
aba: 1 # healthup
abb: 3 # luckup
abc: -3 # total res

# total res branch
abcb: 2

# luck up branch
abbb: 3
#abbaa=>branches go from here
abbaac: 2

# health up brach
abac: 2
abab: 2

# dmg branch
aab: 5
aaab: 3