#define ITSTILIVES 666

enum
{
	NOTHING 						= 0,	
	HEADCRAB_ZOMBIE 				= 1,	
	FORTIFIED_HEADCRAB_ZOMBIE 		= 2,	
	FASTZOMBIE 						= 3,	
	FORTIFIED_FASTZOMBIE 			= 4,
	TORSOLESS_HEADCRAB_ZOMBIE 		= 5,	
	FORTIFIED_GIANT_POISON_ZOMBIE 	= 6,	
	POISON_ZOMBIE 					= 7,	
	FORTIFIED_POISON_ZOMBIE 		= 8,	
	FATHER_GRIGORI 					= 9,
	COMBINE_POLICE_PISTOL			= 10,	
	COMBINE_POLICE_SMG				= 11,	
	COMBINE_SOLDIER_AR2				= 12,
	COMBINE_SOLDIER_SHOTGUN			= 13,	
	COMBINE_SOLDIER_SWORDSMAN		= 14,
	COMBINE_SOLDIER_ELITE			= 15,
	COMBINE_SOLDIER_GIANT_SWORDSMAN	= 16,
	COMBINE_SOLDIER_DDT				= 17,
	COMBINE_SOLDIER_COLLOSS			= 18, //Hetimus
	COMBINE_OVERLORD				= 19, 
	SCOUT_ZOMBIE					= 20,
	ENGINEER_ZOMBIE					= 21,
	HEAVY_ZOMBIE					= 22,
	FLYINGARMOR_ZOMBIE				= 23,
	FLYINGARMOR_TINY_ZOMBIE			= 24,
	KAMIKAZE_DEMO					= 25,
	MEDIC_HEALER					= 26,
	HEAVY_ZOMBIE_GIANT				= 27,
	SPY_FACESTABBER					= 28,
	SOLDIER_ROCKET_ZOMBIE			= 29,
	SOLDIER_ZOMBIE_MINION			= 30,
	SOLDIER_ZOMBIE_BOSS				= 31,
	SPY_THIEF						= 32,
	SPY_TRICKSTABBER				= 33,
	SPY_HALF_CLOACKED				= 34,
	SNIPER_MAIN						= 35,
	DEMO_MAIN						= 36,
	BATTLE_MEDIC_MAIN				= 37,
	GIANT_PYRO_MAIN					= 38,
	COMBINE_DEUTSCH_RITTER			= 39,
	SPY_MAIN_BOSS					= 40,
	
	
	XENO_HEADCRAB_ZOMBIE 				= 41,	
	XENO_FORTIFIED_HEADCRAB_ZOMBIE 		= 42,	
	XENO_FASTZOMBIE 					= 43,	
	XENO_FORTIFIED_FASTZOMBIE 			= 44,
	XENO_TORSOLESS_HEADCRAB_ZOMBIE 		= 45,	
	XENO_FORTIFIED_GIANT_POISON_ZOMBIE 	= 46,	
	XENO_POISON_ZOMBIE 					= 47,	
	XENO_FORTIFIED_POISON_ZOMBIE 		= 48,	
	XENO_FATHER_GRIGORI 				= 49,
	XENO_COMBINE_POLICE_PISTOL			= 50,	
	XENO_COMBINE_POLICE_SMG				= 51,	
	XENO_COMBINE_SOLDIER_AR2			= 52,
	XENO_COMBINE_SOLDIER_SHOTGUN		= 53,	
	XENO_COMBINE_SOLDIER_SWORDSMAN		= 54,
	XENO_COMBINE_SOLDIER_ELITE			= 55,
	XENO_COMBINE_SOLDIER_GIANT_SWORDSMAN	= 56,
	XENO_COMBINE_SOLDIER_DDT			= 57,
	XENO_COMBINE_SOLDIER_COLLOSS		= 58, //Hetimus
	XENO_COMBINE_OVERLORD				= 59, 
	XENO_SCOUT_ZOMBIE					= 60,
	XENO_ENGINEER_ZOMBIE				= 61,
	XENO_HEAVY_ZOMBIE					= 62,
	XENO_FLYINGARMOR_ZOMBIE				= 63,
	XENO_FLYINGARMOR_TINY_ZOMBIE		= 64,
	XENO_KAMIKAZE_DEMO					= 65,
	XENO_MEDIC_HEALER					= 66,
	XENO_HEAVY_ZOMBIE_GIANT				= 67,
	XENO_SPY_FACESTABBER				= 68,
	XENO_SOLDIER_ROCKET_ZOMBIE			= 69,
	XENO_SOLDIER_ZOMBIE_MINION			= 70,
	XENO_SOLDIER_ZOMBIE_BOSS			= 71,
	XENO_SPY_THIEF						= 72,
	XENO_SPY_TRICKSTABBER				= 73,
	XENO_SPY_HALF_CLOACKED				= 74,
	XENO_SNIPER_MAIN					= 75,
	XENO_DEMO_MAIN						= 76,
	XENO_BATTLE_MEDIC_MAIN				= 77,
	XENO_GIANT_PYRO_MAIN				= 78,
	XENO_COMBINE_DEUTSCH_RITTER			= 79,
	XENO_SPY_MAIN_BOSS					= 80,
	
	NAZI_PANZER							= 81,
	BOB_THE_GOD_OF_GODS					= 82,
	NECRO_COMBINE						= 83,
	NECRO_CALCIUM						= 84,
	CURED_FATHER_GRIGORI				= 85,
	
	ALT_COMBINE_MAGE					= 86,
	
	BTD_BLOON							= 87,
	BTD_MOAB							= 88,
	BTD_BFB								= 89,
	BTD_ZOMG							= 90,
	BTD_DDT								= 91,
	BTD_BAD								= 92,
	
	ALT_MEDIC_APPRENTICE_MAGE			= 93,
	SAWRUNNER							= 94,
	
	RAIDMODE_TRUE_FUSION_WARRIOR		= 95,
	ALT_MEDIC_CHARGER					= 96,
	ALT_MEDIC_BERSERKER					= 97,
	
	MEDIVAL_MILITIA						= 98,
	MEDIVAL_ARCHER						= 99,
	MEDIVAL_MAN_AT_ARMS					= 100,
	MEDIVAL_SKIRMISHER					= 101,
	MEDIVAL_SWORDSMAN					= 102,
	MEDIVAL_TWOHANDED_SWORDSMAN			= 103,
	MEDIVAL_CROSSBOW_MAN				= 104,
	MEDIVAL_SPEARMEN					= 105,
	MEDIVAL_HANDCANNONEER				= 106,
	MEDIVAL_ELITE_SKIRMISHER			= 107,
	RAIDMODE_BLITZKRIEG					= 108,
	MEDIVAL_PIKEMAN						= 109,
	ALT_MEDIC_SUPPERIOR_MAGE			= 110,
	CITIZEN								= 111,
	
	MEDIVAL_EAGLE_SCOUT					= 112,
	MEDIVAL_SAMURAI						= 113,
	
	THEADDICTION						= 114,
	THEDOCTOR							= 115,
	BOOKSIMON							= 116,
	ALT_KAHMLSTEIN						= 117,
	
	L4D2_TANK							= 118,
	ALT_COMBINE_DEUTSCH_RITTER			= 119,
	ALT_SNIPER_RAILGUNNER				= 120,
	
	BTD_GOLDBLOON	= 121,
	BTD_BLOONARIUS	= 122,
	BTD_LYCH		= 123,
	BTD_LYCHSOUL	= 124,
	BTD_VORTEX	= 125,
	
	MEDIVAL_RAM	= 126,
	ALT_SOLDIER_BARRAGER = 127,
	ALT_The_Shit_Slapper = 128,
	
	BONEZONE_BASICBONES = 129,
	
	ALT_MECHA_ENGINEER			= 130,
	ALT_MECHA_HEAVY				= 131,
	ALT_MECHA_HEAVYGIANT		= 132,
	ALT_MECHA_PYROGIANT			= 133,
	ALT_MECHA_SCOUT				= 134,
	ALT_DONNERKRIEG				= 135,
	ALT_SCHWERTKRIEG			= 136,
	PHANTOM_KNIGHT				= 137, //Lucian "Blood diamond"
}


public const char NPC_Names[][] =
{
	"nothing",
	"Headcrab Zombie",
	"Fortified Headcrab Zombie",
	"Fast Zombie",
	"Fortified Fast Zombie",
	"Torsoless Headcrab Zombie",
	"Fortified Giant Poison Zombie",
	"Poison Zombie",
	"Fortified Poison Zombie",
	"Father Grigori",
	"Metro Cop",
	"Metro Raider",
	"Combine Rifler",
	"Combine Shotgunner",
	"Combine Swordsman",
	"Combine Elite",
	"Combine Giant Swordsman",
	"Combine DDT",
	"Combine Golden Collos",
	"Combine Overlord",
	"Scout Assulter",
	"Engineer Deconstructor",
	"Heavy Brawler",
	"Flying Armor",
	"Tiny Flying Armor",
	"Kamikaze Demo",
	"Medic Supporter",
	"Giant Heavy Brawler",
	"Spy Facestabber",
	"Soldier Rocketeer",
	"Soldier Minion",
	"Soldier Giant Summoner",
	"Spy Thief",
	"Spy Trickstabber",
	"Half Cloaked Spy",
	"Sniper Main",
	"Demoknight Main",
	"Battle Medic Main",
	"Giant Pyro Main",
	"Combine Deutsch Ritter",
	"X10 Spy Main",
	
	//XENO
	
	"Xeno Headcrab Zombie",
	"Xeno Fortified Headcrab Zombie",
	"Xeno Fast Zombie",
	"Xeno Fortified Fast Zombie",
	"Xeno Torsoless Headcrab Zombie",
	"Xeno Fortified Giant Poison Zombie",
	"Xeno Poison Zombie",
	"Xeno Fortified Poison Zombie",
	"Xeno Father Grigori",
	"Xeno Metro Cop",
	"Xeno Metro Raider",
	"Xeno Combine Rifler",
	"Xeno Combine Shotgunner",
	"Xeno Combine Swordsman",
	"Xeno Combine Elite",
	"Xeno Combine Giant Swordsman",
	"Xeno Combine DDT",
	"Xeno Combine Golden Collos",
	"Xeno Combine Overlord",
	"Xeno Scout Assulter",
	"Xeno Engineer Deconstructor",
	"Xeno Heavy Brawler",
	"Xeno Flying Armor",
	"Xeno Tiny Flying Armor",
	"Xeno Kamikaze Demo",
	"Xeno Medic Supporter",
	"Xeno Giant Heavy Brawler",
	"Xeno Spy Facestabber",
	"Xeno Soldier Rocketeer",
	"Xeno Soldier Minion",
	"Xeno Soldier Giant Summoner",
	"Xeno Spy Thief",
	"Xeno Spy Trickstabber",
	"Xeno Half Cloaked Spy",
	"Xeno Sniper Main",
	"Xeno Demoknight Main",
	"Xeno Battle Medic Main",
	"Xeno Giant Pyro Main",
	"Xeno Combine Deutsch Ritter",
	"Xeno X10 Spy Main",
	
	"Nazi Panzer",
	"Bob the Overgod of gods and destroyer of multiverses",
	"Revived Combine DDT",
	"Spookmaster Boner",
	"Cured Father Grigori",
	"Combine Mage",
	
	"Bloon",
	"Massive Ornery Air Blimp",
	"Brutal Floating Behemoth",
	"Zeppelin of Mighty Gargantuaness",
	"Dark Dirigible Titan",
	"Big Airship of Doom",
	
	
	"Medic Apprentice Mage",
	"Sawrunner",
	"True Fusion Warrior",
	"Medic Charger",
	"Medic Berserker",
	"Militia",
	"Archer",
	"Man-At-Arms",
	"Skirmisher",
	"Long Swordsman",
	"Twohanded Swordsman",
	"Crossbow Man",
	"Spearman",
	"Hand Cannoneer",
	"Elite Skirmisher",
	"Blitzkrieg",
	"Pikeman",
	"Medic Supperior Mage",
	"Rebel",
	"Eagle Scout",
	"Samurai",
	"The Addiction",
	"The Doctor",
	"Book Simon",
	"Kahmlstein",
	"L4D2 Tank",
	"Holy Knight",
	"Sniper Railgunner",
	
	"Gold Bloon",
	"Bloonarius",
	"Gravelord Lych",
	"Lych-Soul",
	"Vortex",
	
	"Capped Ram",
	"Soldier Barrager",
	"The Shit Slapper",
	
	"Basic Bones",
	
	"Mecha Engineer",
	"Mecha Heavy",
	"Mecha Giant Heavy",
	"Mecha Giant Pyro",
	"Mecha Scout",
	"Donnerkrieg",
	"Schwertkrieg",
	"Phantom Knight"
};

public const char NPC_Plugin_Names_Converted[][] =
{
	"npc_nothing",
	"npc_headcrabzombie",
	"npc_headcrabzombie_fortified",
	"npc_fastzombie",
	"npc_fastzombie_fortified",
	"npc_torsoless_headcrabzombie",
	"npc_poisonzombie_fortified_giant",
	"npc_poisonzombie",
	"npc_poisonzombie_fortified",
	"npc_last_survivor",
	"npc_combine_police_pistol",
	"npc_combine_police_smg",
	"npc_combine_soldier_ar2",
	"npc_combine_soldier_shotgun",
	"npc_combine_soldier_swordsman",
	"npc_combine_soldier_elite",
	"npc_combine_soldier_giant_swordsman",
	"npc_combine_soldier_swordsman_ddt",
	"npc_combine_soldier_collos_swordsman",
	"npc_combine_soldier_overlord",
	"npc_zombie_scout_grave",
	"npc_zombie_engineer_grave",
	"npc_zombie_heavy_grave",
	"npc_flying_armor",
	"npc_flying_armor_tiny_swords",
	"npc_kamikaze_demo",
	"npc_medic_healer",
	"npc_zombie_heavy_giant_grave",
	"npc_zombie_spy_grave",
	"npc_zombie_soldier_grave",
	"npc_zombie_soldier_minion_grave",
	"npc_zombie_soldier_giant_grave",
	"npc_spy_thief",
	"npc_spy_trickstabber",
	"npc_spy_half_cloacked_main",
	"npc_sniper_main",
	"npc_zombie_demo_main",
	"npc_medic_main",
	"npc_zombie_pyro_giant_main",
	"npc_combine_soldier_deutsch_ritter",
	"npc_spy_boss",
	
	//XENO
	
	"npc_xeno_headcrabzombie",
	"npc_xeno_headcrabzombie_fortified",
	"npc_xeno_fastzombie",
	"npc_xeno_fastzombie_fortified",
	"npc_xeno_torsoless_headcrabzombie",
	"npc_xeno_poisonzombie_fortified_giant",
	"npc_xeno_poisonzombie",
	"npc_xeno_poisonzombie_fortified",
	"npc_xeno_last_survivor",
	"npc_xeno_combine_police_pistol",
	"npc_xeno_combine_police_smg",
	"npc_xeno_combine_soldier_ar2",
	"npc_xeno_combine_soldier_shotgun",
	"npc_xeno_combine_soldier_swordsman",
	"npc_xeno_combine_soldier_elite",
	"npc_xeno_combine_soldier_giant_swordsman",
	"npc_xeno_combine_soldier_swordsman_ddt",
	"npc_xeno_combine_soldier_collos_swordsman",
	"npc_xeno_combine_soldier_overlord",
	"npc_xeno_zombie_scout_grave",
	"npc_xeno_zombie_engineer_grave",
	"npc_xeno_zombie_heavy_grave",
	"npc_xeno_flying_armor",
	"npc_xeno_flying_armor_tiny_swords",
	"npc_xeno_kamikaze_demo",
	"npc_xeno_medic_healer",
	"npc_xeno_zombie_heavy_giant_grave",
	"npc_xeno_zombie_spy_grave",
	"npc_xeno_zombie_soldier_grave",
	"npc_xeno_zombie_soldier_minion_grave",
	"npc_xeno_zombie_soldier_giant_grave",
	"npc_xeno_spy_thief",
	"npc_xeno_spy_trickstabber",
	"npc_xeno_spy_half_cloacked_main",
	"npc_xeno_sniper_main",
	"npc_xeno_zombie_demo_main",
	"npc_xeno_medic_main",
	"npc_xeno_zombie_pyro_giant_main",
	"npc_xeno_combine_soldier_deutsch_ritter",
	"npc_xeno_spy_boss",
	
	"npc_panzer",
	"npc_bob_the_overlord",
	"npc_necromancy_combine",
	"npc_necromancy_calcium",
	"npc_cured_last_survivor",
	
	"npc_alt_combine_soldier_mage",
	
	"npc_bloon",
	"",
	"",
	"",
	"",
	"",
	"npc_alt_medic_apprentice_mage",
	"npc_sawrunner",
	"npc_true_fusion_warrior",
	"npc_alt_medic_charger",
	"npc_alt_medic_berserker",
	"npc_medival_militia",
	"npc_medival_archer",
	"npc_medival_man_at_arms",
	"npc_medival_skrirmisher",
	"npc_medival_swordsman",
	"npc_medival_twohanded_swordsman",
	"npc_medival_crossbow",
	"npc_medival_spearmen",
	"npc_medival_handcannoneer",
	"npc_medival_elite_skirmisher",
	"npc_blitzkrieg",
	"npc_medival_pikeman",
	"npc_alt_medic_supperior_mage",
	"npc_citizen",
	"npc_medival_eagle_scout",
	"npc_medival_samurai",
	"",
	"",
	"",
	"npc_alt_kahml",
	"npc_l4d2_tank",
	"npc_alt_combine_soldier_deutsch_ritter",
	"npc_alt_sniper_railgunner",
	"",
	"",
	"",
	"",
	"",
	"npc_medival_ram",
	"npc_alt_soldier_barrager",
	"npc_alt_the_shit_slapper",
	
	"npc_basicbones",
	
	"npc_alt_mecha_engineer",
	"npc_alt_mecha_heavy",
	"npc_alt_mecha_heavy_giant",
	"npc_alt_mecha_pyro_giant",
	"npc_alt_mecha_scout",
	"npc_alt_donnerkrieg",
	"npc_alt_schwertkrieg",
	"npc_phantom_knight"
};